/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "CHANGE": "更改",
    "CHALLENGES": "挑战",
    "Challenges": "挑战",
    "Achievement requirement here": "这里需要成就",
    "Highest Level": "最高等级",
    "Highest Level:": "最高等级：",
    "True Randomness": "真正的随机性",
    "UPGRADES": "升级",
    "UPGRADE!": "可升级!",
    "Upgrade Prism LVL": "升级 棱镜 等级",
    "Gravitational Waves": "引力波",
    "Gravity Well": "重力井",
    "GRAVITY WELL": "重力井",
    "Growth Factor": "生长因子",
    "Growth Interval": "生长间隔",
    "Heads up! PP gain past LVL 60 is based on highest level instead": "小心！超过 60级 的 PP 增益基于最高等级",
    "Helium Avalanche": "氦雪崩",
    "Helium production is boosted based on how many watts you have": "氦气产量会根据您拥有的瓦数而增加",
    "Helium production is boosted based on how much helium you have": "氦气产量取决于您拥有多少氦气",
    "Helium production is boosted based on Prism LVL": "基于 棱镜等级 提高氦气产量",
    "Helium production is boosted based on unspent hydrogen": "基于未用完的氢气提高了氦气的产量",
    "Helium production is disabled": "氦气生产被禁用",
    "Hidden Achievement Hints": "隐藏的成就提示",
    "Ultracharge": "超充电",
    "Unautomated clicks are boosted a further +32% for every Autoclicker tier": "每个 自动点击器 层级级的非自动点击进一步提高了 32%",
    "Uninhibited Flux": "不受约束的通量",
    "Unlocks 100% Capacitance mode, giving a 8x boost on Discharge": "解锁 100% 电容模式，放电时提升 8 倍",
    "Unlocks 50% Capacitance mode, which gives a 4x boost on Discharge": "解锁 50% 电容模式，使放电提升 4 倍",
    "Unlocks 75% Capacitance mode, giving a 6x boost on Discharge": "解锁 75% 电容模式，放电时提升 6 倍",
    "Unlocks a customizable Auto-Prestige setting that automatically switches between Peak and PP mode": "解锁可在峰值和 PP 模式之间自动切换的可自定义 自动声望 设置",
    "Unlocks a new prestige layer": "解锁新的声望层级",
    "Unlocks an automator that will automatically activate EXP Overclock when its cooldown is over": "解锁一个自动机，当它的冷却时间结束时会自动激活 经验超频",
    "Unlocks an upgrade that generates a boost to EXP production, increasing over time": "解锁升级，提高经验生产，随着时间的推移而增加",
    "Unlocks an upgrade that gives an additional multiplier to EXP with active and idle modes": "解锁升级，在活动和放置模式下为 经验 提​​供额外的乘数",
    "Unlocks an upgrade that gives random amounts of extra EXP on all clicks": "解锁升级，在所有点击中随机获得额外的 经验",
    "Unlocks an upgrade that multiplies all EXP production": "解锁使所有 经验生产 成倍增长的升级",
    "Unlocks automated mode switching for Capacitor, automatically switching to the highest available mode": "解锁电容器的自动模式切换，自动切换到最高可用模式",
    "Unlocks automation for all upgrades": "解锁所有升级的自动化",
    "Unlocks automation for Prestige": "为 声望 解锁自动化",
    "Unlocks automation for Prestige upgrades": "解锁 声望 升级的自动化",
    "Unlocks automation for pushing levels": "解锁推动等级的自动化",
    "Unlocks automation for Reactor core upgrades": "解锁反应堆核心升级的自动化",
    "Unlocks automation for Reboot": "为重新启动解锁自动化",
    "Unlocks Challenges": "解锁挑战",
    "Unlocks Quantize automation": "解锁量化自动化",
    "Unlocks the EXP Capacitor, which takes some of your EXP production and stores it": "解锁 经验电容器，它会获取您的一些 经验 生产并将其存储起来",
    "Unlocks the EXP Overclocker, which boosts EXP 3x for 45 seconds": "解锁 经验电容器，将 经验 提​​升 3 倍，持续 45 秒",
    "Unlocks the Gravity Well": "解锁重力井",
    "Unlocks the Nuclear Reactor": "解锁核反应堆",
    "Unlocks three additional modes for Auto-Prestige configuration": "为 自动声望 配置解锁三种额外模式",
    "Unlocks Time mode for Auto-Reboot": "解锁自动重启的时间模式",
    "ACHIEVEMENTS": "成就",
    "Confirmation": "确认",
    "Current EXP": "当前经验",
    "Current Mode Time: ": "当前模式时间：",
    "Current Photons": "当前光子",
    "Current Prestige Points": "当前声望点",
    "ACTIVE": "激活",
    "Advanced Auto-Prestiging": "高级自动声望",
    "Advanced Auto-Reboot": "高级自动重启",
    "All challenges can now be completed up to 20 times": "所有挑战现在最多可以完成 20 次",
    "All EXP production is divided by 1.000 trillion, Multi-Prestige and Reboot Residue do not apply": "所有经验产量除以 1.000 trillion，批量声望 和 重启残留 不适用",
    "All EXP production is divided by 10.00 quadrillion, AMP Conversion does not apply": "所有 EXP 产量除以 10.00 万亿，AMP 转换不适用",
    "All EXP production reduces to zero over 30 seconds": "所有 EXP 产量在 30 秒内降至零",
    "All Upgrades tab things except EXP Boost and Autoclicker are disabled": "除 经验提升 和 自动点击器 之外的所有升级选项卡内容均已禁用",
    "Also allows Auto-Prestige configuration": "还允许自动声望配置",
    "Also allows you to Discharge at 0 seconds": "还可以让你在 0 秒内放电",
    "Also has an average watts/sec display": "还具有平均瓦特/秒显示",
    "Also unlocks automation for Discharge": "还解锁了 Discharge 的自动化",
    "Also unlocks Peak mode for Advanced auto-Prestige, automatically prestiging at peak AMP/sec": "还为高级自动声望解锁峰值模式，以峰值 AMP/秒自动声望",
    "Also unlocks Smart Auto-Discharge, which automatically Discharges when best to do so": "还解锁智能自动放电，它会在最好的时候自动放电",
    "AMP Conversion": "AMP 转换",
    "AMP Conversion now gives 100% of your pending AMP instead": "AMP 转换现在提供 100% 的待处理 AMP",
    "AMP Efficiency": "放大器效率",
    "Beta Decay": "贝塔衰减",
    "Breaks the limits, allowing you to go beyond LVL 60": "突破极限，让你超越 LVL 60",
    "BUY MAX": "买最大",
    "BUY ONE": "买一个",
    "Completions past 12 also give a helium production boost": "超过 12 年的完工也提高了氦气的产量",
    "D: Discharge Capacitor": "D：放电电容器",
    "Dark matter also boosts helium production at a reduced amount": "暗物质还能以减少的量增加氦的产量",
    "DARK UPGRADES": "黑暗升级",
    "DELETE SAVE": "删除存档",
    "Depth Power": "深度功率",
    "Deuterium Channeling": "氘通道",
    "Deuterium Power": "氘动力",
    "Deuterium Power now also boosts 3x instead": "氘能量现在也提高了 3 倍",
    "Deuterium Power now boosts hydrogen gains 2.50x per tier instead": "氘动力现在将每层级的氢气增益提高 2.50 倍",
    "DISABLED": "已禁用",
    "Discharge automation is also now unlocked with the EXP Capacitor instead of High Voltage I": "放电自动化现在也可以使用 EXP 电容器而不是高压 I 解锁",
    "Discharge is 2x stronger": "放电强度提高 2 倍",
    "DISCHARGE!": "释放！",
    "Discord": "Discord",
    "Dual Power": "双电源",
    "E: Exit Challenge": "E：退出挑战",
    "Ease of Completion": "易于完成",
    "ENABLED": "已启用",
    "Energize": "通电",
    "ENTER CHALLENGE": "进入挑战",
    "Enter Reboot": "进入重启",
    "Entering a challenge will attempt to Reboot, and will reset without giving watts if you cannot": "进入挑战将尝试重新启动，如果您不能，将在不给瓦特的情况下重置",
    "EXIT CHALLENGE": "退出挑战",
    "EXP Capacitor": "经验电容",
    "EXP Factor": "经验系数",
    "EXP Fluctuation": "经验波动",
    "EXP Fluctuation is twice as strong": "经验波动增强两倍",
    "EXP Flux": "经验通量",
    "EXP Flux now increases 5x faster, and has a 5x higher cap": "经验通量现在提高 5 倍，上限提高 5 倍",
    "EXP Flux permanently increases 5x faster and has a 5x higher cap": "经验通量永久提高 5 倍，上限提高 5 倍",
    "EXP Overclocker": "经验超频器",
    "EXP Overclocker and EXP Capacitor are disabled": "经验超频器 和 经验电容器 被禁用",
    "Expert Auto-Reboot": "专家自动重启",
    "EXPORT": "导出",
    "Extended Difficulty": "扩展难度",
    "Fusion": "聚变",
    "Hydrogen now no longer requires 98,304 watts to be gained": "氢气现在不再需要 98,304 瓦才能获得",
    "IMPORT": "导入",
    "IGNORE": "忽略",
    "Infinicharge": "限充电",
    "LVL": "等级",
    "M: Buy all upgrades (on upgrades tab": "M：购买所有升级（在升级选项卡上",
    "Magnified Flux": "放大通量",
    "STATISTICS": "统计",
    "MAX ALL": "全部",
    "Max Capacity": "最大容量",
    "MAX HALF": "最大一半",
    "MAXED": "最大化",
    "mg helium": "毫克氦",
    "Multi-Prestige": "多重威望",
    "NEXT": "下一页",
    "Next PP at LVL 69": "LVL 69 的下一个 PP",
    "NO": "不",
    "Notation": "符号",
    "NUCLEAR REACTOR CORES": "核反应堆堆芯",
    "O: Activate Overclocker": "O：激活超频器",
    "Open Sesame": "芝麻开门",
    "Overachievements": "成绩优异",
    "P: Prestige": "P：声望",
    "Patience": "耐心",
    "Patience will also boost prestige stat by up to 30x": "耐心还将使声望值提高多达 30 倍",
    "Patience will also boost Times Prestiged stat by up to 30x": "耐心还将使 Times Prestiged 统计数据提高 30 倍",
    "PEAK": "顶峰",
    "Photonic Infusion": "光子注入",
    "photons": "光子",
    "PHOTONS": "光子",
    "Photosensitivity Mode": "感光模式",
    "PP Auto-upgrade Configuration": "PP自动升级配置",
    "PP Auto-Upgrading": "PP 自动升级",
    "PP is immediately granted on leveling up rather than Prestiging": "PP在升级而不是声望时立即授予",
    "PP Progress Bar": "PP 进度条",
    "PP Shift": "PP 移位",
    "PP Upgrades": "PP 升级",
    "PRESTIGE": "声望",
    "Prestige Power": "威望力量",
    "PRESTIGE!": "声望！",
    "PREV": "上一页",
    "Priority": "优先事项",
    "Priority Reset Layer": "优先重置层级",
    "PRISM": "棱镜",
    "producing 1x AMP gain": "产生 1x AMP 增益",
    "Q: Quantize": "问：量化",
    "Quantize Confirmation": "量化确认",
    "Quantize no longer resets Challenge completions": "量化不再重置挑战完成",
    "QUANTIZE!": "量化！",
    "QUANTUM": "量子",
    "Quantum Privilege": "量子特权",
    "QUANTUM UPGRADES": "量子升级",
    "R: Reboot": "R：重启",
    "REACTOR": "反应堆",
    "REBOOT": "重启",
    "Reboot Confirmation": "重启确认",
    "Reboot in 6 Prestiges or less": "在 6 次或更少的声望中重新启动",
    "Reboot Residue": "重启残留",
    "REBOOT!": "重启！",
    "Rebooting will now also give hydrogen": "重启现在也会产生氢气",
    "Recharging": "充电",
    "Requires": "需要",
    "RESET HOTKEYS": "重置热键",
    "RESPEC!": "洗点！",
    "SAVE": "保存",
    "SETTINGS": "设置",
    "Shift+1-6: Toggle auto-upgrade (on upgrades tab": "Shift+1-6：切换自动升级（在升级选项卡上",
    "Shift+D: Toggle auto-Discharge": "Shift+D：切换自动放电",
    "Shift+O: Toggle auto-Overclock": "Shift+O：切换自动超频",
    "Shift+P: Toggle auto-Prestige": "Shift+P：切换自动声望",
    "Shift+R: Toggle auto-Reboot": "Shift+R：切换自动重启",
    "SHOW ALL": "显示所有",
    "Smart Auto-Prestige": "智能汽车威望",
    "Smart Auto-Prestige Configuration": "智能自动声望配置",
    "Snowball Effect": "雪球效应",
    "Space: EXP button": "空格：经验按钮",
    "stacks with Magnified Flux if you have it, making it uncapped": "如果有的话，可以与放大通量叠加，使其不封顶",
    "stacks with Supercharge": "带有增压的堆栈",
    "Stacks with the first four Starter Kit Prestige upgrades": "与前四个 入门套件声望 升级叠加",
    "STANDARD": "标准",
    "Stretched Time": "延长时间",
    "STRICT": "严格的",
    "Supercharge": "增压",
    "switching Discharges": "开关放电",
    "Switchpoint": "切换点",
    "The active/idle switch for EXP Battery is removed, and both modes are now in effect simultaneously": "EXP电池的激活/放置开关被移除，两种模式现在同时生效",
    "The Auto-Prestige panel will now display average AMP gained per second": "自动声望面板现在将显示每秒平均获得的 AMP",
    "The cooldown on EXP Overclocker is removed entirely, making Overclocker always active": "经验超频器 的冷却时间被完全移除，使 超频器 始终处于激活状态",
    "The Enter Reboot boost based on achievements now works multiplicatively instead of additively": "基于成就的 进入重启 提升现在以乘法而不是加法的方式工作",
    "The Generator": "发电机",
    "The only EXP multipliers that apply are AMP, Challenge boosts, and Helium": "唯一适用的经验乘数是 AMP、挑战提升和氦气",
    "The Snowball Effect perk becomes stronger": "雪球效应特权变得更强",
    "They don't do anything by themselves, and are only for spending": "他们自己什么都不做，只为消费",
    "This applies retroactively": "这追溯适用",
    "Amplification Points": "增强点",
    "Atomic Refraction": "原子折射",
    "Auto-Capacitance": "自电容",
    "Auto-Overclocking": "自动超频",
    "Auto-Prestige AMP": "自动声望放大器",
    "Auto-Prestige Configuration": "自动声望配置",
    "Auto-Prestige Level": "自动声望等级",
    "Auto-Prestige Mode": "自动声望模式",
    "Auto-Prestige PP": "自动声望PP",
    "Auto-Prestige Time (in seconds)": "自动声望时间（以秒为单位）",
    "Auto-Prestiging": "自动声望",
    "Auto-Quantize": "自动量化",
    "Auto-Quantize Configuration": "自动量化配置",
    "Auto-Quantize Mode": "自动量化模式",
    "Auto-Quantize Photons": "自动量化光子",
    "Auto-Quantize Time (in seconds)": "自动量化时间（以秒为单位）",
    "Auto-Reactor": "自动反应器",
    "Auto-Reactor Configuration": "自动反应器配置",
    "Auto-Reboot": "自动重启",
    "Auto-Reboot Configuration": "自动重启配置",
    "Auto-Reboot Mode": "自动重启模式",
    "Auto-Reboot Time (in seconds)": "自动重启时间（以秒为单位）",
    "Auto-Reboot Watts": "自动重启瓦",
    "Auto-Upgrading": "自动升级",
    "Autoclicker": "自动点击器",
    "Autoclicking": "自动点击",
    "AUTOMATIC": "自动的",
    "Automation": "自动化",
    "Begin Push Time (in seconds)": "开始推送时间（以秒为单位）",
    "Beta": "测试版",
    "Capacitance Mode": "电容模式",
    "CONFIG": "配置",
    "Deuterium Importance": "氘重要性",
    "Discharge at (seconds)": "放电时间（秒）",
    "EXP Battery": "经验电池",
    "EXP Boost": "经验提升",
    "EXP Overclocker now stays active twice as long": "经验超频器 现在保持激活的时间是原来的两倍",
    "EXP production is boosted +5% for every achievement completed": "经验 产量就会提高 +5%",
    "EXP production is boosted based on how many times you have Prestiged": "经验 产量会根据您拥有声望的次数而增加",
    "EXP production is boosted based on how much spare PP you have": "经验值产量取决于你有多少备用 PP",
    "EXP production is boosted based on unspent photons": "基于未使用的光子提高 经验 产量",
    "EXP production is boosted based on your fastest Quantum Iteration": "根据您最快的量子迭代提高 EXP 产量",
    "EXP production is boosted based on your fastest Reboot": "经验值产量会根据你最快的重启而提升",
    "EXP production is boosted based on your highest level": "根据您的最高等级提高经验值",
    "Fastest Prestige": "最快的声望",
    "Fastest Quantum Iteration": "最快的量子迭代",
    "Fastest Reboot": "最快重启",
    "g hydrogen": "克氢气",
    "Game saved": "游戏已保存",
    "GENERATOR": "发电机",
    "GENERATOR PERKS": "发电机津贴",
    "Get all 108 challenge completions to unlock a new prestige layer...": "完成所有 108 个挑战以解锁新的声望层级...",
    "Go Nuclear": "去核",
    "Heads up! PP gain past LVL 60 is based on highest level instead)": "小心!PP增益超过60级是基于最高等级的)",
    "IDLE": "放置",
    "Left/Right: Change tab": "左/右：更改选项卡",
    "LEVEL": "等级",
    "Level Color": "级别颜色",
    "Levels require more EXP the more levels you have": "您拥有的级别越多，级别需要的经验就越多",
    "Limit Break": "极限突破",
    "LONG": "长",
    "Longer Prestiges give more AMP (up to 10 seconds)": "更长的声望提供更多的 AMP（最多 10 秒）",
    "M: Buy all upgrades (on upgrades tab)": "M：购买所有升级（在升级选项卡上）",
    "Made by Zakuro": "扎库罗制作",
    "MILLION": "MILLION",
    "Photons gained are based on your Highest Level (Current Iteration)": "获得的光子基于您的最高级别（当前迭代）",
    "Priority Mode": "优先模式",
    "Reboot for pending PP": "重启待处理的 PP",
    "Shift+1-6: Toggle auto-upgrade (on upgrades tab)": "Shift+1-6：切换自动升级（在升级选项卡上）",
    "Smart Mode": "智能模式",
    "Spare Power": "备用电源",
    "stacks with Magnified Flux if you have it, making it uncapped)": "如果有的话，可以与放大通量叠加，使其不封顶）",
    "stacks with Supercharge)": "带增压的堆栈）",
    "Stacks with the first four Starter Kit Prestige upgrades)": "与前四个 入门套件声望 升级叠加）",
    "Starting Mode": "启动模式",
    "Stored EXP can later be discharged at a 2x boost": "存储的 EXP 稍后可以以 2 倍的提升释放",
    "switching Discharges)": "开关放电）",
    "This applies retroactively)": "这追溯适用）",
    "Time Played (Current Iteration)": "游戏时长（当前游戏）",
    "Time Played (Current Prestige)": "游戏时长（当前声望）",
    "Time Played (Current Reboot)": "游戏时长（当前重启）",
    "Time to wait in Peak mode (in seconds)": "峰值模式下的等待时间（以秒为单位）",
    "Time to wait in PP mode (in seconds)": "在 PP 模式下等待的时间（以秒为单位）",
    "Times Prestiged": "声望次数",
    "To complete a challenge you must Reboot with the required amount of spare PP": "要完成挑战，您必须使用所需数量的备用 PP 重新启动",
    "Total EXP Multiplier": "总经验乘数",
    "Total Manual EXP Multipler": "总手动 EXP 倍数",
    "Total Prestige Points": "总声望点",
    "Total Quantum Iterations": "总量子迭代",
    "Visual Update Rate": "视觉更新率",
    "Watt Efficiency: ???": "瓦特效率：？？？",
    "watts": "瓦",
    "WATTS": "瓦特",
    "WEAK": "虚弱的",
    "You begin Reboots with every PP upgrade up to EXP Overclocker already purchased": "每当重新启动时，获得足以购买到限制突破的经验超频器",
    "You begin Reboots with every PP upgrade up to Limit Break already purchased": "每当重新启动时，获得足以购买到限制突破的PP",
    "You can do multiple completions per Challenge attempt, and completions are given automatically": "您可以在每次挑战尝试中完成多个任务，并且自动完成任务",
    "You gain 1 extra prestige stat for every 200 levels gained": "每获得 200 个等级，您就会获得 1 个额外的声望值",
    "You gain 1 extra Times Prestiged stat for every 200 levels when you Prestige": "当你声望时，你每 200 级获得 1 个额外的时代声望属性",
    "You gain 20% of your pending AMP every second": "您每秒获得 20% 的待处理 AMP",
    "You gain more watts on Reboot the farther past 200,000 PP you go": "越过 200,000 PP，您在重新启动时获得的功率就越多",
    "You must surpass your highest level to gain more AMP, Patience does not apply": "你必须超过你的最高等级才能获得更多的AMP，耐心不适用",
    "You permanently keep 25% of your Times Prestiged stat every Reboot": "每次重新启动时，您都会永久保留 25% 的 时间声望 统计数据",
    "A: Toggle all automation": "A：切换所有自动化",
    "TIME": "时间",
    "All Prestige upgrades purchased": "购买的所有声望升级",
    "All rules from the first four challenges, simultaneously": "前四个挑战的所有规则，同时",
    "All upgrades on the Upgrades tab have twice as many free tiers": "“升级”选项卡上的所有升级都有两倍的免费等级",
    "All upgrades require 5x as many levels": "所有升级都需要 5 倍的关卡",
    "EXP Overclocker cooldown time is halved": "经验超频器 冷却时间减半",
    "EXP Overclocker cooldown time is halved a second time": "经验超频器 冷却时间第二次减半",
    "AMP Limit (0 for no limit)": "AMP 上限（0 表示无限制）",
    "PURCHASED": "已购买",
    "Push it to the limit": "挑战极限",
    "SHOW IMPORTANT": "显示重要的",
    "Square one": "广场一",
    "The only RNG in the game": "游戏中唯一的RNG",
    "Whoa, we're halfway there": "哇，我们已经成功了一半",
    "HIDE BOUGHT": "隐藏已购买",
    "Level up!": "升级!",
    "Spontaneous Fortune": "自发的财富",
    "There is a 1 in 7,777 chance every second you will get this achievement": "每秒有 7,777 分之一的机会获得此成就",
    "Unlock everything on the Upgrades tab": "解锁升级选项卡上的所有内容",
    "Unlock EXP Factor": "解锁经验系数",
    "Unlock EXP Fluctuation": "解锁经验波动",
    "A whole lot of nothing": "一大堆什么都没有",
    "Buy all 40 Prestige upgrades": "购买所有 40 种声望升级",
    "Caps at 20x)": "上限为 20 倍）",
    "Decathlevel": "十级",
    "Did it for the memes": "这样做是为了模因",
    "Enter a meme number into any input box": "在任意输入框中输入 模因数字",
    "EXP Simulator v2.3.103": "经验模拟器 v2.3.103",
    "Gain no EXP for 10 minutes": "10分钟内没有经验",
    "Get every achievement": "获得每一项成就",
    "Hot minute": "热身",
    "1-6: Buy upgrade (on upgrades tab)": "1-6：购买升级（在升级选项卡上）",
    "a very long time": "很长一段时间",
    "Automated EXP/click": "自动 经验/点击",
    "Exported to clipboard": "存档已导出到剪贴板",
    "Maxed!": "最大！",
    "Total Automated EXP Multipler": "总自动经验乘数",
    "(switching Discharges)": "(切换放电)",
    "See you in another life": "下辈子见",
    "Speedy clicking": "快速点击",
    "The sky's the limit": "前途无量",
    "Nowhere to go but up": "除了向上，无处可去",
    "Who wants to be a billionaire?": "谁想成为亿万富翁?",
    "9-Volt": "9 伏",
    "Amplified": "放大",
    "Reach 100x EXP Flux boost": "达到 100 倍 EXP 通量提升",
    "Stonks": "斯托克斯",
    "Unlock EXP Battery": "解锁经验电池",
    "Unlock EXP Capacitor": "解锁经验电容",
    "Unlock EXP Flux": "解锁经验通量",
    "Unlock EXP Overclocker": "解锁 EXP 超频器",
    "Get Limit Break": "获得极限突破",
    "Level 100 boss": "100级boss",
    "Now we're getting somewhere": "现在我们正在到达某个地方",
    "What do all these levels even do?": "所有这些等级甚至可以做什么？",
    "Protip: you can hold the EXP button": "小提示：可以长按经验按钮",
    "Save deleted": "存档已删除",
    "Time Played": "游戏时长",
    "Total Clicks": "总点击次数",
    "Total EXP": "总经验",
    "Total EXP Multipler": "总经验乘数",
    "Standby": "已就绪",
    "US national debt": "美国国债",
    "But can it run Crysis?": "但它可以运行孤岛危机吗？",
    "Time well spent": "时间花得值",
    "Haha AMP go brrrrr": "哈哈 AMP 去 brrrrr",
    "Push it to the limit x5": "将其推到上限 x5",
    "Sir, do you know how fast you were going?": "先生，您知道您的速度有多快吗？",
    "The entire world economy": "全球经济",
    "The EXP flows within you": "经验在你体内流动",
    "Blast off": "发射",
    "Welcome to hell": "欢迎来到地狱",
    "Unfathomable wealth": "深不可测的财富",
    "To hell and back again": "下地狱再回来",
    "To infinity and not beyond": "到无限而不是超越",
    "To the end of space and time": "到时空的尽头",
    "Top ten numbers you'll never use": "你永远不会使用的前十个数字",
    "Total helium boost from all challenges: 1.953e6x": "所有挑战的总氦气提升：1.953e6x",
    "Tutorial completed!": "教程完成！",
    "Ultimate completionism": "终极完成主义",
    "Unlock all 28 Generator Perks": "解锁所有 28 个发电机特权",
    "Unlock the Gravity Well": "解锁重力井",
    "Unlock the Nuclear Reactor": "解锁核反应堆",
    "Unlocks 100% Capacitance mode, giving a 16x boost on Discharge": "解锁 100% 电容模式，放电时提升 16 倍",
    "Unlocks 50% Capacitance mode, which gives a 8x boost on Discharge": "解锁 50% 电容模式，可将放电提升 8 倍",
    "Unlocks 75% Capacitance mode, giving a 12x boost on Discharge": "解锁 75% 电容模式，放电时提升 12 倍",
    "Unlocks an upgrade that gives an additional multiplier to EXP": "解锁为 EXP 提​​供额外乘数的升级",
    "Unlocks four additional modes for Auto-Prestige configuration": "为 自动声望 配置解锁四种附加模式",
    "Upgrade every core of the Reactor": "升级反应堆的每个核心",
    "Watt Efficiency: +2.439e7 watts/sec": "瓦特效率：+2.439e7 瓦/秒",
    "WE HAVE REAHCED MXAIMUN VLELOCIPY": "我们已经达到了 最大极速",
    "We're not in Kansas anymore": "我们不在堪萨斯了",
    "Well the digits keep comin and they don't stop comin": "好吧，数字不断出现，它们不会停止出现",
    "When the levels are not so easy": "当关卡不是那么容易时",
    "Where no man has gone before": "以前没有人去过的地方",
    "With great haste": "匆匆忙忙",
    "With great power comes great EXP": "强大的力量带来巨大的经验",
    "YES": "是的",
    "You could stop at five or six Prestiges, or just none": "你可以停在五六个声望，或者根本没有",
    "You must surpass your highest level to gain more AMP, Patience and AMP Conversion do not apply": "您必须超过最高等级才能获得更多 AMP，耐心和 AMP 转换不适用",
    "You're still here?": "你还在这里？",
    "Your parents wouldn't be proud": "你的父母不会感到骄傲",
    "Also starts with automation unlocked": "也从解锁自动化开始",
    "Complete a challenge while using ??? notation": "使用 ??? 完成挑战 符号",
    "COMPLETED!": "已完成！",
    "Does not apply to challenges)": "不适用于挑战）",
    "Highest Level (Current Reboot)": "最高级别（当前重启）",
    "Multi-Prestige, Reboot Residue, Ease of Completion do not apply": "多重威望、重启残留物、完成难度不适用",
    "Reboot without Prestiging": "无需声望即可重新启动",
    "SCIENTIFIC": "科学的",
    "SMART": "聪明的",
    "Stored EXP can later be discharged at a 4x boost": "存储的 EXP 稍后可以以 4 倍的提升释放",
    "Stuck between no eyes and a hard place": "卡在没有眼睛和坚硬的地方之间",
    "45 digits is a lot": "45位数字太多了",
    "Reboot in under 1 hour": "不到 1 小时重新启动",
    "Reboot in under 1 minute": "不到 1 分钟重新启动",
    "Reboot in under 1 second": "1秒内重启",
    "Reboot in under 10 minutes": "不到 10 分钟重新启动",
    "Satisfied yet?": "还满意吗？",
    "So big it breaks Long notation": "这么大，它打破了长符号",
    "Stare into the abyss": "凝视深渊",
    "Started from the bottom now we here": "从底部开始现在我们在这里",
    "Tesseract one": "正方体一",
    "That was only half as difficult": "那只是困难的一半",
    "That's some serious markup": "这是一些严重的标记",
    "The big one-oh-oh-oh-oh-oh": "大一哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦",
    "The definition of diminishing returns": "收益递减的定义",
    "The grandmaster of level ups": "升级大师",
    "The pursuit of madness": "疯狂的追求",
    "This bad boy can fit so much hydrogen in it": "这个坏男孩可以装这么多氢气",
    "And this is to go even further beyond": "这将更进一步",
    "At the speed of light": "以光速",
    "Big numbers for a big boy": "大男孩的大数字",
    "Blood, sweat, and EXP": "血、汗、EXP",
    "Calculated": "计算出来的",
    "Complete a single challenge 12 times": "完成单项挑战 12 次",
    "Complete Challenge I for the first time": "首次完成挑战 I",
    "Complete Challenge II for the first time": "首次完成挑战 II",
    "Complete Challenge III for the first time": "首次完成挑战 III",
    "Complete Challenge IV for the first time": "首次完成挑战 IV",
    "Complete Challenge IX for the first time": "首次完成挑战 IX",
    "Complete Challenge V for the first time": "首次完成挑战 V",
    "Complete Challenge VI for the first time": "首次完成挑战 VI",
    "Complete Challenge VII for the first time": "首次完成挑战 VII",
    "Complete Challenge VIII for the first time": "首次完成挑战 VIII",
    "Congration, you done it": "恭喜，你做到了",
    "Critical mass": "临界质量",
    "Cube one": "立方体一",
    "Cycle of insanity": "疯狂循环",
    "Day in, day out": "日复一日",
    "Dazzling brilliance": "耀眼的光彩",
    "Definitely can't count this on my hands": "绝对不能指望我的手",
    "Delayed gratification": "迟来的喜悦",
    "Did you miss them?": "你想念他们吗？",
    "Discharge the Capacitor while the Overclocker is active": "在超频器处于活动状态时对电容器放电",
    "Endless growth": "无尽的成长",
    "Escape velocity": "逃逸速度",
    "Even Zakuro didn't expect you to make it this far": "连扎库罗都没料到你能走到这一步",
    "Event horizon": "事件视界",
    "EXP comes to those who wait": "经验值来到等待的人",
    "EXP singularity": "经验奇点",
    "Full potential unlocked": "释放全部潜力",
    "Fusion mailed": "融合邮寄",
    "GAS GAS GAS": "煤气煤气煤气",
    "Groundhog day": "土拨鼠日",
    "Halfway to infinity": "一半到无穷大",
    "Helium is love Helium is life": "氦是爱 氦是生命",
    "Honestly bro, this is just a really heckin big number... like I can't even think of any good name for this one so this is what you get": "老实说，这只是一个非常大的数字......就像我什至想不出这个名字的好名字，所以这就是你得到的",
    "Honestly quite sizeable": "老实说相当大",
    "Hungolomghnonoloughongous": "Hungolomghnonoloughongous",
    "I can see my house from here": "我可以从这里看到我的房子",
    "I dunno man I don't think it's enough progress": "我不知道，我不认为这是足够的进步",
    "I like a little challenge in my life": "我喜欢生活中的小挑战",
    "I like my women like I like my numbers": "我喜欢我的女人，就像我喜欢我的数字一样",
    "I tried so hard and got so far": "我努力了，走到了这一步",
    "I've become so numb": "我变得如此麻木",
    "I've got the power": "我已经拥有了力量",
    "In case of implosion look at implosion": "如果发生内爆，请查看内爆",
    "It's okay I lost track too": "没关系我也迷路了",
    "Jack of all trades": "万事通",
    "Less than zero": "小于零",
    "Let its light inside you": "让它的光在你里面",
    "Like kicking a brick wall": "就像踢砖墙一样",
    "Make 1.000e30 mg helium/sec": "使 1.000e30 毫克氦/秒",
    "Make 1.000e60 mg helium/sec": "使 1.000e60 毫克氦/秒",
    "Making the most out of your reset": "充分利用您的重置",
    "More! More! More!!": "更多的！更多的！更多的！！",
    "Nigh unstoppable": "几乎势不可挡",
    "Not bad, kid": "不错，孩子",
    "Objects in well are heavier than they appear": "井中的物体比看起来更重",
    "Oh, the places you'll go": "哦，你要去的地方",
    "On a whole new level": "在一个全新的水平",
    "On the exponential scale this isn't really that big": "在指数规模上，这并不是那么大",
    "One chonker number": "一串数字",
    "Oops! All pushing": "哎呀！全部推",
    "Overexperienced": "经验丰富",
    "Picking up the pace": "加快步伐",
    "Progress from lost progress": "从失去的进步中取得进步",
    "Quantize in under 1 hour": "在 1 小时内量化",
    "Quantize in under 1 minute": "在 1 分钟内量化",
    "Quantize in under 10 seconds": "在 10 秒内量化",
    "Quantize in under 30 seconds": "在 30 秒内量化",
    "Quantize in under 5 minutes": "在 5 分钟内量化",
    "Reach ∞ kg dark matter": "达到∞公斤暗物质",
    "*notices your EXP*": "*注意你的经验*",
    "#intentionalfeature": "#intentionalfeature",
    "A real grindset": "真正的磨具",
    "AAA": "AAA",
    "Absolute unit": "绝对单位",
    "Ace of one trade": "一笔交易的王牌",
    "Activate the Generator": "激活生成器",
    "Addicted to EXP": "沉迷于经验",
    "All hail the Prism": "所有人都欢呼棱镜",
    "All is lost again": "一切都再次失去",
    "Now you're thinking with photons!": "现在你在用光子思考！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'PP': 'PP',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Total Clicks (All Time": "总点击次数 (所有时间",
    "Total Clicks (Current Iteration": "总点击次数（当前游戏",
    "Total EXP (Current Iteration": "总经验（当前游戏",
    "Total EXP (Current Prestige": "总经验（当前声望",
    "Total Clicks (Current Prestige": "总点击次数（当前声望",
    "Total EXP (Current Reboot": "总经验（当前重启",
    "Total Clicks (Current Reboot": "总点击次数（当前重启",
    "Total EXP (All Time": "总经验（所有时间",
    "Total Reboots": "总重启次数",
    "Challenge ": "挑战 ",
    "Achievement slot ": "成就插槽 ",
    "High Voltage ": "高压 ",
    "Highest Level (All Time": "最高等级（所有时间",
    "Highest Level (Current Iteration": "最高级别（当前游戏",
    "Hydrogen Savings Proportion": "节氢率",
    "Current Level": "当前等级",
    "Current Hydrogen": "当前的氢",
    "EXP Automation Power": "经验自动化力量",
    "EXP/click": "经验/点击",
    "Generator Power": "发电机功率",
    "Generator requirements": "发电机要求",
    "Hue": "色调",
    "Jumpstart ": "快速启动 ",
    "kg dark matter": "kg 暗物质",
    "LVL ": "等级 ",
    "Manual EXP/click": "手动 经验/点击",
    "Manual Labor ": "手工劳动 ",
    "Starter Kit ": "入门套件 ",
    "Speed Power ": "速度力量 ",
    "Technological Gift ": "科技礼物 ",
    "Time Played (All Time": "游戏时长（所有时间",
    "Extra Cycles ": "额外循环 ",
    "Completions: ": "完成: ",
    "Current Mode Time: ": "当前模式时间：",
    "EXP boost from completions: ": "完成后的 经验 提升：",
    "EXP Discount ": "经验折扣 ",
    "EXP Overclocker now boosts EXP ": "经验超频器 现在提升 经验",
    "Achievements earned: ": "获得的成就：",
    "ACTIVATE": "激活",
    "AMP Efficiency: ": "AMP效率：",
    "Base EXP Production: ": "基础经验生产：",
    "Prism LVL": "棱镜等级",
    "Stored EXP: ": "存储的经验：",
    "Total EXP boost from all challenges: ": "总经验提升来自所有挑战：",
    "Reach LVL ": "达到等级 ",
    "Effective EXP Production: ": "有效的经验生产：",
    "EXP boost from Achievements: ": "来自成就的 经验 提升：",
    "Reach Prism LVL ": "达到 棱镜 等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    ":\n": ":\n",
    ":": ":",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "x helium production": "x 氦气生产",
    "x hydrogen gains": "x 氢气增益",
    "x (Discharging)": "x（放电）",
    " EXP (Discharging)": " 经验 (放电)",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) million$/,
    /^([\d\.]+) million AMP$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\:([\d\.,]+)\:([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) PP$/,
    /^([\d\.]+)e([\d\.,]+) AMP$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Get (.+) all time EXP$/, '获得 $1 全部时间的经验'],
    [/^Get (.+) AMP$/, '获得 $1 AMP'],
    [/^\(Next PP at LVL 69\)$/, '\(下一个 PP 在 $1 级\)'],
    [/^If Discharged: (.+) EXP \(Not Active\)$/, '如果放电：$1 经验（未激活）'],
    [/^Play for (.+) hour$/, '玩 $1 小时'],
    [/^Play for (.+) hours$/, '玩 $1 小时'],
    [/^Prestige (.+) time$/, '声望 $1 次'],
    [/^Reboot (.+) time$/, '重启 $1 次'],
    [/^Quantize (.+) time$/, '量化 $1 次'],
    [/^Prestige (.+) times$/, '声望 $1 次'],
    [/^Reboot (.+) times$/, '重启 $1 次'],
    [/^Quantize (.+) times$/, '量化 $1 次'],
    [/^Get (.+) total challenge completions$/, '总共完成 $1 次挑战'],
    [/^also creating (.+)$/, '还制造了 $1'],
    [/^All EXP production is divided by (.+), AMP Conversion does not apply$/, '所有 经验 产量除以 $1，AMP 转换不适用'],
    [/^All EXP production is divided by (.+)$/, '所有 经验 产量除以 $1'],
    [/^Boosts from completions: (.+)x EXP, (.+)x helium$/, '完成提升：$1x 经验，$2x 氦气'],
    [/^If Discharged: (.+) EXP (.+)$/, '如果放电：$1 经验 $2'],
    [/^producing (.+)x AMP gain$/, '产生 $1x AMP 增益'],
    [/^Reboot in 0 Prestiges or less$/, '重启获得 $1 声望或更少'],
    [/^Boosting (.+)x$/, '提升 $1x'],
    [/^Reach (.+) clicks\/s on the Autoclicker$/, '在自动点击器上达到 $1 次点击/秒'],
    [/^Next PP at LVL(.+)$/, '下一个 PP 在 等级 $1'],
    [/^creating (.+)x EXP production$/, '使 经验生产 x$1'],
    [/^Tier (.+): ([\d\.,]+) clicks\/s$/, '层级 $1: $2 点击\/秒'],
    [/^Tier (.+): ([\d\.,]+) clicks$/, '层级 $1: $2 点击'],
    [/^Tier (.+): ([\d\.,]+)x EXP(.+)production$/, '层级 $1: $2x 经验$3生产'],
    [/^Tier (.+): ([\d\.,]+)x automated EXP(.+)production$/, '层级 $1: $2x 自动化经验$3生产'],
    [/^Tier (.+): ([\d\.,]+)x manual EXP(.+)production$/, '层级 $1: $2x 手动经验$3生产'],
    [/^Tier (.+): ([\d\.,]+)x manual EXP\n(.+)production$/, '层级 $1: $2x 手动经验\n$3生产'],
    [/^Tier (.+): \+([\d\.,]+)x flux\/min$/, '层级 $1: \+$2x 通量\/分钟'],
    [/^Tier (.+): \+(.+) max extra(.+)EXP\/click$/, '层级 $1: \+$2 最大额外$3经验\/点击'],
    [/^Tier (.+): \+([\d\.,]+) max extra\n(.+)EXP\/click$/, '层级 $1: \+$2 最大额外$3\n经验\/点击'],
    [/^Tier (.+): ([\d\.,]+)x EXP\/click$/, '层级 $1: $2x 经验\/点击'],
    [/^Tier (.+): (.+)x EXP\/click (.+)\/min\)$/, '层级 $1: $2x 经验\/点击 $3\/分钟）'],
    [/^Tier (.+): \+(.+) EXP\/click$/, '层级 $1: \+$2 经验\/点击'],
    [/^EXP Battery is now (.+) stronger$/, '经验电池现在强了 $1 倍'],
    [/^All Upgrades require (.+) fewer levels$/, '所有升级所需的等级减少 $1'],
    [/^All upgrades require (.+) fewer levels$/, '所有升级所需的等级减少 $1'],
    [/^All further Prestiges start at LVL (.+); Prestiging now requires LVL (.+)$/, '所有其他声望从 $1 级 开始； 声望现在需要 $2 级'],
    [/^Unautomated clicks are (.+) stronger$/, '非自动点击的强度提高了 $1 倍'],
	[/^(.+) \/ (.+) EXP$/, '$1 \/ $2 经验'],
	[/^(.+) \- (.+) EXP$/, '$1 \- $2 经验'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^(.+) Total EXP$/, '$1 总经验'],
    [/^([\d\.,]+) free tiers on every upgrade on the Upgrades tab$/, '“升级”选项卡上的每次升级都有 $1 免费层级'],
    [/^([\d\.,]+) extra free tiers on every upgrade on the Upgrades tab$/, '“升级”选项卡上的每次升级都有 $1 额外免费层级'],
    [/^([\d\.,]+) challenge completions required$/, '需要完成 $1 个挑战'],
    [/^([\d\.,]+) PP$/, '$1 PP'],
    [/^([\d\.,]+) free tiers from Starter Kit$/, '$1 免费层级 来自 入门套件'],
    [/^\+([\d\.,]+) PP$/, '\+$1 PP'],
    [/^([\d\.,]+) watt$/, '$1 瓦'],
    [/^([\d\.,]+)x watt gain boost$/, '$1x 瓦 增益提升'],
    [/^\+([\d\.,]+) watt$/, '\+$1 瓦'],
    [/^([\d\.]+)s Left$/, '$1秒 剩余'],
    [/^([\d\.,]+)\:([\d\.,]+) Left$/, '$1:$2 剩余'],
    [/^([\d\.,]+)\:([\d\.,]+)\:([\d\.,]+) Left$/, '$1:$2:$3 剩余'],
    [/^([\d\.,]+) click\/sec$/, '$1 点击\/秒'],
    [/^([\d\.]+) million EXP$/, '$1 million 经验'],
    [/^([\d\.]+)s of EXP$/, '$1s 经验'],
    [/^\+([\d\.,]+) EXP$/, '\+$1 经验'],
    [/^([\d\.,]+) AMP$/, '$1 AMP'],
    [/^\+([\d\.,]+) AMP$/, '\+$1 AMP'],
    [/^([\d\.,]+) watts$/, '$1 瓦'],
    [/^([\d\.,]+) clicks\/s$/, '$1 点击/秒'],
    [/^([\d\.]+) million watts$/, '$1 million 瓦'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) EXP$/, '$1 经验'],
    [/^([\d\.]+) quadrillion EXP$/, '$1 quadrillion 经验'],
    [/^([\d\.]+) trillion EXP$/, '$1 trillion 经验'],
    [/^([\d\.]+) billion EXP$/, '$1 billion 经验'],
    [/^(.+) EXP\/sec$/, '$1 经验\/秒'],
    [/^([\d\.]+) AMP\/sec$/, '$1 AMP\/秒'],
    [/^([\d\.]+)e([\d\.,]+) AMP\/sec$/, '$1e$2 AMP\/秒'],
    [/^([\d\.,]+) AMP\/sec$/, '$1 AMP\/秒'],
    [/^([\d\.,]+) photons$/, '$1 光子'],
    [/^\+([\d\.,]+) photons$/, '\+$1 光子'],
    [/^\+([\d\.,]+) free tiers from Starter Kit$/, '\+$1 入门套件中的免费层级'],
    [/^([\d\.]+)e([\d\.,]+) EXP$/, '$1e$2 经验'],
    [/^([\d\.]+)e([\d\.,]+) EXP\/sec \(Discharging\)$/, '$1e$2 经验\/秒 \(放电\)'],
    [/^([\d\.]+)e([\d\.,]+) watts$/, '$1e$2 瓦'],
    [/^([\d\.]+)e([\d\.,]+) mg helium\/sec$/, '$1e$2 毫克 氦气\/秒'],
    [/^([\d\.]+)e([\d\.,]+) spare PP$/, '$1e$2 备用PP'],
    [/^([\d\.]+)e([\d\.,]+) g hydrogen$/, '$1e$2 克 氢气'],
    [/^([\d\.]+)e([\d\.,]+)x hydrogen gains$/, '$1e$2x 氢气增益'],
    [/^([\d\.]+)e\+([\d\.,]+) photons$/, '$1e\+$2 光子'],
    [/^([\d\.]+)e([\d\.,]+) photons$/, '$1e$2 光子'],
    [/^\-([\d\.]+) photons$/, '\-$1 光子'],
    [/^\-([\d\.]+)e([\d\.,]+) photons$/, '\-$1e$2 光子'],
    [/^([\d\.]+) billion photons$/, '$1 billion 光子'],
    [/^([\d\.]+) trillion photons$/, '$1 trillion 光子'],
    [/^([\d\.]+) sextillion photons$/, '$1 sextillion 光子'],
    [/^([\d\.]+) octillion photons$/, '$1 octillion 光子'],
    [/^([\d\.]+) duodecillion photons$/, '$1 duodecillion 光子'],
    [/^([\d\.]+) quadrillion photons$/, '$1 quadrillion 光子'],
    [/^([\d\.]+) quattuordecillion photons$/, '$1 quattuordecillion 光子'],
    [/^([\d\.,]+) million photons$/, '$1 million 光子'],
    [/^([\d\.,]+) quintillion photons$/, '$1 quintillion 光子'],
    [/^([\d\.]+) nonillion photons$/, '$1 quintillion 光子'],
    [/^([\d\.]+)x helium production$/, '$1x 氦 生产'],
    [/^([\d\.]+)x hydrogen gains$/, '$1x 氢 增益'],
    [/^([\d\.]+) g hydrogen$/, '$1 克 氢气'],
    [/^\-([\d\.]+) g hydrogen$/, '\-$1 克 氢气'],
    [/^\+([\d\.]+) g hydrogen$/, '\+$1 克 氢气'],
    [/^(.+) mg base helium\/sec$/, '$1 毫克 基础 氦气\/秒'],
    [/^([\d\.]+) mg helium\/sec$/, '$1 毫克 氦气\/秒'],
    [/^\+([\d\.]+) mg helium\/sec$/, '\+$1 毫克 氦气\/秒'],
    [/^([\d\.,]+) g hydrogen$/, '$1 克 氢气'],
    [/^([\d\.,]+) spare PP$/, '$1 备用PP'],
    [/^Page ([\d\.,]+)$/, '页数 $1'],
    [/^Core ([\d\.,]+)$/, '核心 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Goal: (.+) PP$/, '目标：$1 PP'],
    [/^Currently: ([\d\.]+)x$/, '当前：$1x'],
    [/^Currently: (.+)x\)$/, '当前：$1x\)'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);