/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "CHANGE": "更改",
    "CHALLENGES": "挑战",
    "Challenges": "挑战",
    "Achievement requirement here": "这里需要成就",
    "Highest Level": "最高等级",
    "Highest Level:": "最高等级：",
    "True Randomness": "真正的随机性",
    "UPGRADES": "升级",
    "UPGRADE!": "升级了!",
    "Upgrade Prism LVL": "升级 棱镜 等级",
    "Gravitational Waves": "引力波",
    "Gravity Well": "重力井",
    "GRAVITY WELL": "重力井",
    "Growth Factor": "生长因子",
    "Growth Interval": "生长间隔",
    "Heads up! PP gain past LVL 60 is based on highest level instead": "小心！超过 60级 的 PP 增益基于最高等级",
    "Helium Avalanche": "氦雪崩",
    "Helium production is boosted based on how many watts you have": "氦气产量会根据您拥有的瓦数而增加",
    "Helium production is boosted based on how much helium you have": "氦气产量取决于您拥有多少氦气",
    "Helium production is boosted based on Prism LVL": "基于 棱镜等级 提高氦气产量",
    "Helium production is boosted based on unspent hydrogen": "基于未用完的氢气提高了氦气的产量",
    "Helium production is disabled": "氦气生产被禁用",
    "Hidden Achievement Hints": "隐藏的成就提示",
    "Ultracharge": "超充电",
    "Unautomated clicks are boosted a further +32% for every Autoclicker tier": "每个 自动点击器 层级的非自动点击进一步提高了 32%",
    "Uninhibited Flux": "不受约束的通量",
    "Unlocks 100% Capacitance mode, giving a 8x boost on Discharge": "解锁 100% 电容模式，放电时提升 8 倍",
    "Unlocks 50% Capacitance mode, which gives a 4x boost on Discharge": "解锁 50% 电容模式，使放电提升 4 倍",
    "Unlocks 75% Capacitance mode, giving a 6x boost on Discharge": "解锁 75% 电容模式，放电时提升 6 倍",
    "Unlocks a customizable Auto-Prestige setting that automatically switches between Peak and PP mode": "解锁可在峰值和 PP 模式之间自动切换的可自定义 自动声望 设置",
    "Unlocks a new prestige layer": "解锁新的声望层",
    "Unlocks an automator that will automatically activate EXP Overclock when its cooldown is over": "解锁一个自动机，当它的冷却时间结束时会自动激活 经验超频",
    "Unlocks an upgrade that generates a boost to EXP production, increasing over time": "解锁升级，提高经验生产，随着时间的推移而增加",
    "Unlocks an upgrade that gives an additional multiplier to EXP with active and idle modes": "解锁升级，在活动和空闲模式下为 经验 提​​供额外的乘数",
    "Unlocks an upgrade that gives random amounts of extra EXP on all clicks": "解锁升级，在所有点击中随机获得额外的 经验",
    "Unlocks an upgrade that multiplies all EXP production": "解锁使所有经验值倍增的升级",
    "Unlocks automated mode switching for Capacitor, automatically switching to the highest available mode": "解锁电容器的自动模式切换，自动切换到最高可用模式",
    "Unlocks automation for all upgrades": "解锁所有升级的自动化",
    "Unlocks automation for Prestige": "为 声望 解锁自动化",
    "Unlocks automation for Prestige upgrades": "解锁 声望 升级的自动化",
    "Unlocks automation for pushing levels": "解锁推动水平的自动化",
    "Unlocks automation for Reactor core upgrades": "解锁反应堆核心升级的自动化",
    "Unlocks automation for Reboot": "为重新启动解锁自动化",
    "Unlocks Challenges": "解锁挑战",
    "Unlocks Quantize automation": "解锁量化自动化",
    "Unlocks the EXP Capacitor, which takes some of your EXP production and stores it": "解锁 经验电容器，它会获取您的一些 经验 生产并将其存储起来",
    "Unlocks the EXP Overclocker, which boosts EXP 3x for 45 seconds": "解锁 经验电容器，将 经验 提​​升 3 倍，持续 45 秒",
    "Unlocks the Gravity Well": "解锁重力井",
    "Unlocks the Nuclear Reactor": "解锁核反应堆",
    "Unlocks three additional modes for Auto-Prestige configuration": "为 自动声望 配置解锁三种额外模式",
    "Unlocks Time mode for Auto-Reboot": "解锁自动重启的时间模式",
    "ACHIEVEMENTS": "成就",
    "Confirmation": "确认",
    "Current EXP": "当前经验",
    "Current Mode Time: ": "当前模式时间：",
    "Current Photons": "当前光子",
    "Current Prestige Points": "当前声望点",
    "ACTIVE": "激活",
    "Advanced Auto-Prestiging": "高级自动声望",
    "Advanced Auto-Reboot": "高级自动重启",
    "All challenges can now be completed up to 20 times": "所有挑战现在最多可以完成 20 次",
    "All EXP production is divided by 1.000 trillion, Multi-Prestige and Reboot Residue do not apply": "所有经验产量除以 1.000 trillion，批量声望 和 重启残留 不适用",
    "All EXP production is divided by 10.00 quadrillion, AMP Conversion does not apply": "所有 EXP 产量除以 10.00 万亿，AMP 转换不适用",
    "All EXP production reduces to zero over 30 seconds": "所有 EXP 产量在 30 秒内降至零",
    "All Upgrades tab things except EXP Boost and Autoclicker are disabled": "除 EXP Boost 和 Autoclicker 之外的所有升级选项卡内容均已禁用",
    "Also allows Auto-Prestige configuration": "还允许自动声望配置",
    "Also allows you to Discharge at 0 seconds": "还可以让你在 0 秒内放电",
    "Also has an average watts/sec display": "还具有平均瓦特/秒显示",
    "Also unlocks automation for Discharge": "还解锁了 Discharge 的自动化",
    "Also unlocks Peak mode for Advanced auto-Prestige, automatically prestiging at peak AMP/sec": "还为高级自动声望解锁峰值模式，以峰值 AMP/秒自动声望",
    "Also unlocks Smart Auto-Discharge, which automatically Discharges when best to do so": "还解锁智能自动放电，它会在最好的时候自动放电",
    "AMP Conversion": "AMP 转换",
    "AMP Conversion now gives 100% of your pending AMP instead": "AMP 转换现在提供 100% 的待处理 AMP",
    "AMP Efficiency": "放大器效率",
    "Beta Decay": "贝塔衰减",
    "Breaks the limits, allowing you to go beyond LVL 60": "突破极限，让你超越 LVL 60",
    "BUY MAX": "买最大",
    "BUY ONE": "买一个",
    "Completions past 12 also give a helium production boost": "超过 12 年的完工也提高了氦气的产量",
    "D: Discharge Capacitor": "D：放电电容器",
    "Dark matter also boosts helium production at a reduced amount": "暗物质还能以减少的量增加氦的产量",
    "DARK UPGRADES": "黑暗升级",
    "DELETE SAVE": "删除保存",
    "Depth Power": "深度功率",
    "Deuterium Channeling": "氘通道",
    "Deuterium Power": "氘动力",
    "Deuterium Power now also boosts 3x instead": "氘能量现在也提高了 3 倍",
    "Deuterium Power now boosts hydrogen gains 2.50x per tier instead": "氘动力现在将每层的氢气增益提高 2.50 倍",
    "DISABLED": "已禁用",
    "Discharge automation is also now unlocked with the EXP Capacitor instead of High Voltage I": "放电自动化现在也可以使用 EXP 电容器而不是高压 I 解锁",
    "Discharge is 2x stronger": "放电强度提高 2 倍",
    "DISCHARGE!": "释放！",
    "Discord": "不和谐",
    "Dual Power": "双电源",
    "E: Exit Challenge": "E：退出挑战",
    "Ease of Completion": "易于完成",
    "ENABLED": "已启用",
    "Energize": "通电",
    "ENTER CHALLENGE": "进入挑战",
    "Enter Reboot": "进入重启",
    "Entering a challenge will attempt to Reboot, and will reset without giving watts if you cannot": "进入挑战将尝试重新启动，如果您不能，将在不给瓦特的情况下重置",
    "EXIT CHALLENGE": "退出挑战",
    "EXP Capacitor": "经验电容",
    "EXP Factor": "经验系数",
    "EXP Fluctuation": "经验波动",
    "EXP Fluctuation is twice as strong": "经验波动是两倍强",
    "EXP Flux": "经验通量",
    "EXP Flux now increases 5x faster, and has a 5x higher cap": "经验通量现在提高 5 倍，上限提高 5 倍",
    "EXP Flux permanently increases 5x faster and has a 5x higher cap": "经验通量永久提高 5 倍，上限提高 5 倍",
    "EXP Overclocker": "经验超频者",
    "EXP Overclocker and EXP Capacitor are disabled": "经验超频器 和 经验电容器 被禁用",
    "Expert Auto-Reboot": "专家自动重启",
    "EXPORT": "导出",
    "Extended Difficulty": "扩展难度",
    "Fusion": "聚变",
    "Hydrogen now no longer requires 98,304 watts to be gained": "氢气现在不再需要 98,304 瓦才能获得",
    "IMPORT": "导入",
    "IGNORE": "忽略",
    "Infinicharge": "限充电",
    "LVL": "等级",
    "M: Buy all upgrades (on upgrades tab": "M：购买所有升级（在升级选项卡上",
    "Magnified Flux": "放大通量",
    "STATISTICS": "统计",
    "MAX ALL": "全部",
    "Max Capacity": "最大容量",
    "MAX HALF": "最大一半",
    "MAXED": "最大化",
    "mg helium": "毫克氦",
    "Multi-Prestige": "多重威望",
    "NEXT": "下一个",
    "Next PP at LVL 69": "LVL 69 的下一个 PP",
    "NO": "不",
    "Notation": "符号",
    "NUCLEAR REACTOR CORES": "核反应堆堆芯",
    "O: Activate Overclocker": "O：激活超频器",
    "Open Sesame": "芝麻开门",
    "Overachievements": "成绩优异",
    "P: Prestige": "P：声望",
    "Patience": "耐心",
    "Patience will also boost prestige stat by up to 30x": "耐心还将使声望值提高多达 30 倍",
    "Patience will also boost Times Prestiged stat by up to 30x": "耐心还将使 Times Prestiged 统计数据提高 30 倍",
    "PEAK": "顶峰",
    "Photonic Infusion": "光子注入",
    "photons": "光子",
    "PHOTONS": "光子",
    "Photosensitivity Mode": "感光模式",
    "PP Auto-upgrade Configuration": "PP自动升级配置",
    "PP Auto-Upgrading": "PP 自动升级",
    "PP is immediately granted on leveling up rather than Prestiging": "PP在升级而不是声望时立即授予",
    "PP Progress Bar": "PP 进度条",
    "PP Shift": "PP 移位",
    "PP Upgrades": "PP 升级",
    "PRESTIGE": "声望",
    "Prestige Power": "威望力量",
    "PRESTIGE!": "声望！",
    "PREV": "上一篇",
    "Priority": "优先事项",
    "Priority Reset Layer": "优先重置层",
    "PRISM": "棱镜",
    "producing 1x AMP gain": "产生 1x AMP 增益",
    "Q: Quantize": "问：量化",
    "Quantize Confirmation": "量化确认",
    "Quantize no longer resets Challenge completions": "量化不再重置挑战完成",
    "QUANTIZE!": "量化！",
    "QUANTUM": "量子",
    "Quantum Privilege": "量子特权",
    "QUANTUM UPGRADES": "量子升级",
    "R: Reboot": "R：重启",
    "REACTOR": "反应堆",
    "REBOOT": "重启",
    "Reboot Confirmation": "重启确认",
    "Reboot in 6 Prestiges or less": "在 6 次或更少的声望中重新启动",
    "Reboot Residue": "重启残留",
    "REBOOT!": "重启！",
    "Rebooting will now also give hydrogen": "重启现在也会产生氢气",
    "Recharging": "充电",
    "Requires": "需要",
    "RESET HOTKEYS": "重置热键",
    "RESPEC!": "尊重！",
    "SAVE": "节省",
    "SETTINGS": "设置",
    "Shift+1-6: Toggle auto-upgrade (on upgrades tab": "Shift+1-6：切换自动升级（在升级选项卡上",
    "Shift+D: Toggle auto-Discharge": "Shift+D：切换自动放电",
    "Shift+O: Toggle auto-Overclock": "Shift+O：切换自动超频",
    "Shift+P: Toggle auto-Prestige": "Shift+P：切换自动声望",
    "Shift+R: Toggle auto-Reboot": "Shift+R：切换自动重启",
    "SHOW ALL": "显示所有",
    "Smart Auto-Prestige": "智能汽车威望",
    "Smart Auto-Prestige Configuration": "智能自动声望配置",
    "Snowball Effect": "雪球效应",
    "Space: EXP button": "空格：经验按钮",
    "stacks with Magnified Flux if you have it, making it uncapped": "如果有的话，可以与放大通量叠加，使其不封顶",
    "stacks with Supercharge": "带有增压的堆栈",
    "Stacks with the first four Starter Kit Prestige upgrades": "与前四个 入门套件声望 升级叠加",
    "STANDARD": "标准",
    "Stretched Time": "延长时间",
    "STRICT": "严格的",
    "Supercharge": "增压",
    "switching Discharges": "开关放电",
    "Switchpoint": "切换点",
    "The active/idle switch for EXP Battery is removed, and both modes are now in effect simultaneously": "EXP电池的激活/空闲开关被移除，两种模式现在同时生效",
    "The Auto-Prestige panel will now display average AMP gained per second": "自动声望面板现在将显示每秒平均获得的 AMP",
    "The cooldown on EXP Overclocker is removed entirely, making Overclocker always active": "经验超频器 的冷却时间被完全移除，使 超频器 始终处于激活状态",
    "The Enter Reboot boost based on achievements now works multiplicatively instead of additively": "基于成就的 进入重启 提升现在以乘法而不是加法的方式工作",
    "The Generator": "发电机",
    "The only EXP multipliers that apply are AMP, Challenge boosts, and Helium": "唯一适用的经验乘数是 AMP、挑战提升和氦气",
    "The Snowball Effect perk becomes stronger": "雪球效应特权变得更强",
    "They don't do anything by themselves, and are only for spending": "他们自己什么都不做，只为消费",
    "This applies retroactively": "这追溯适用",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Total Clicks (All Time": "总点击次数 (所有时间",
    "Total Clicks (Current Iteration": "总点击次数（当前游戏",
    "Total EXP (Current Iteration": "总经验（当前游戏",
    "Total EXP (Current Prestige": "总经验（当前声望",
    "Total Clicks (Current Prestige": "总点击次数（当前声望",
    "Total EXP (Current Reboot": "总经验（当前重启",
    "Total Clicks (Current Reboot": "总点击次数（当前重启",
    "Total EXP (All Time": "总经验（所有时间",
    "Total Reboots": "总重启次数",
    "Challenge ": "挑战 ",
    "Achievement slot ": "成就插槽 ",
    "High Voltage ": "高压 ",
    "Highest Level (All Time": "最高等级（所有时间",
    "Highest Level (Current Iteration": "最高级别（当前游戏",
    "Hydrogen Savings Proportion": "节氢率",
    "Current Level": "当前等级",
    "Current Hydrogen": "当前的氢",
    "EXP Automation Power": "经验自动化力量",
    "EXP/click": "经验/点击",
    "Generator Power": "发电机功率",
    "Generator requirements": "发电机要求",
    "Hue": "色调",
    "Jumpstart ": "快速启动 ",
    "kg dark matter": "kg 暗物质",
    "LVL ": "等级 ",
    "Manual EXP/click": "手动 经验/点击",
    "Manual Labor ": "手工劳动 ",
    "Starter Kit ": "入门套件 ",
    "Speed Power ": "速度力量 ",
    "Technological Gift ": "科技礼物 ",
    "Time Played (All Time": "游戏时长（所有时间",
    "Extra Cycles ": "额外循环 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    ":\n": ":\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Tier ([\d\.,]+): ([\d\.,]+) clicks$/, '层 $1: $2 点击'],
    [/^Tier ([\d\.,]+): \+([\d\.,]+) EXP\/click$/, '层 $1: \+$2 经验\/点击'],
    [/^EXP Battery is now (.+) stronger$/, '经验电池现在强了 $1 倍'],
    [/^All Upgrades require (.+) fewer levels$/, '所有升级所需的等级减少 $1'],
    [/^All upgrades require (.+) fewer levels$/, '所有升级所需的等级减少 $1'],
    [/^All further Prestiges start at LVL (.+); Prestiging now requires LVL (.+)$/, '所有其他声望从 $1 级 开始； 声望现在需要 $2 级'],
    [/^Unautomated clicks are (.+) stronger$/, '非自动点击的强度提高了 $1 倍'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) PP$/, '$1 PP'],
    [/^([\d\.,]+) watts$/, '$1 瓦特'],
    [/^([\d\.,]+) photons$/, '$1 光子'],
    [/^([\d\.,]+) million photons$/, '$1 million 光子'],
    [/^([\d\.,]+) quintillion photons$/, '$1 quintillion 光子'],
    [/^([\d\.]+) g hydrogen$/, '$1 克 氢气'],
    [/^Core ([\d\.,]+)$/, '核心 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Goal: (.+) PP$/, '目标：$1 PP'],
    [/^Currently: ([\d\.]+)x$/, '当前：$1x'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);